---
- name: Create jenkins user
  user:
    name: jenkins
    home: /home/jenkins
    shell: /bin/bash

- name: Create .ssh folder
  file:
    path: /home/jenkins/.ssh
    state: directory
    mode: 0700
    owner: jenkins

- name: Add jenkins key
  copy:
    src: authorized_keys
    dest: /home/jenkins/.ssh/authorized_keys
    mode: 0600
    owner: jenkins
    group: jenkins

- name: Grant privileges without password
  lineinfile:
    line: "jenkins ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers
    regexp: '^jenkins'

